server:
 servlet:
  context-path: /oauth-resource
 port: 8083

logging:
 level:
  org: INFO
  
#endpoints.cors.allowed-origins=*

#server.ssl.key-store-type=PKCS12
## The path to the keystore containing the certificate
#server.ssl.key-store=classpath:keystore/alisson.p12
## The password used to generate the certificate
#server.ssl.key-store-password=123456
## The alias mapped to the certificate
#server.ssl.key-alias=alisson
#
##server.ssl.enabled=true


paypal:
 clientID: ATHIgUVy2euO1u8PPm0ozrkMl8Ph8ZynnL8e0n83wD5F-CABD4BZZ8U1n3wmLb_Z5xi2C8KvpaGeU6_B
 clientSecret: ENfcxAo90CIiE_f9aq6mktUmodtYhmXqLIqqhl6s0zkdQht8ibzraSODbwLaN7porUvqAZSVNrJ-2cuv
 executionMode: sandbox
 url:
  checkout:
   orders: https://api.sandbox.paypal.com/v2/checkout/orders/%s
  gettoken: https://api.sandbox.paypal.com/v1/oauth2/token


spring:
 autoconfigure:
  exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

mongodb:
 primary:
   host: localhost
   port: 27017
   database: second

host:
 full:
  dns:
   auth:
    link: https://localhost:8888/oauth-server/oauth/authorize

app:
 client:
  id: userBuildClientIdPassword
  secret: secret
auth:
 server:
  schem: https

