version: '3'

services:
  
#  mongo:
#    image: 'mongo:3.4.1'
#    ports:
#      - '27017:27017'
#    depends_on:
#      - postgres-compose
#    networks:
#      - compose-network
   
#  authorization-server:
#    image: authorization-server
#    ports:
#        - "8081:8081"
#    depends_on:
#      - postgres-compose
#    networks:
#      - compose-network

#  elasticsearch:
#      image: elasticsearch:2.4.5
#      ports:
#        - "9200:9200"
#        - "9300:9300"

  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
    ports:
      - "15432:5432"
    networks:
      - compose-network
    container_name: postgres-container
      
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pedrina.alisson@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123"
    ports:
      - "16543:80"
    depends_on:
      - postgres-compose
    networks:
      - compose-network

networks: 
  compose-network:
    driver: bridge
